# -*- coding: utf-8 -*-
"""执行绑定（scaffold.py 自动生成的草稿）"""

KIND_CONTROL='hass_control'; KIND_QUERY='hass_query'; KIND_SCRIPT='script'; KIND_SCENE='scene'

BINDINGS = {
  'light_living_on': {'device': '客厅灯', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.lumi_acn017_8c9b_right_switch_service', 'reply': '客厅灯开了', 'undo': 'light_living_off'},
  'light_living_off': {'device': '客厅灯', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.lumi_acn017_8c9b_right_switch_service', 'reply': '客厅灯关了', 'undo': 'light_living_on'},
  'light_wallwash_on': {'device': '洗墙灯', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.lumi_acn017_8c9b_left_switch_service', 'reply': '洗墙灯开了', 'undo': 'light_wallwash_off'},
  'light_wallwash_off': {'device': '洗墙灯', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.lumi_acn017_8c9b_left_switch_service', 'reply': '洗墙灯关了', 'undo': 'light_wallwash_on'},
  'light_dining_on': {'device': '餐厅灯', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.lumi_acn018_8c45_left_switch_service', 'reply': '餐厅灯开了', 'undo': 'light_dining_off'},
  'light_dining_off': {'device': '餐厅灯', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.lumi_acn018_8c45_left_switch_service', 'reply': '餐厅灯关了', 'undo': 'light_dining_on'},
  'light_dining_spot_on': {'device': '餐厅射灯', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.lumi_acn017_7e5c_right_switch_service', 'reply': '餐厅射灯开了', 'undo': 'light_dining_spot_off'},
  'light_dining_spot_off': {'device': '餐厅射灯', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.lumi_acn017_7e5c_right_switch_service', 'reply': '餐厅射灯关了', 'undo': 'light_dining_spot_on'},
  'light_kitchen_on': {'device': '厨房灯', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.lumi_acn017_7e5c_left_switch_service', 'reply': '厨房灯开了', 'undo': 'light_kitchen_off'},
  'light_kitchen_off': {'device': '厨房灯', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.lumi_acn017_7e5c_left_switch_service', 'reply': '厨房灯关了', 'undo': 'light_kitchen_on'},
  'light_hallway_on': {'device': '过道灯', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.lumi_acn018_8c45_middle_switch_service', 'reply': '过道灯开了', 'undo': 'light_hallway_off'},
  'light_hallway_off': {'device': '过道灯', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.lumi_acn018_8c45_middle_switch_service', 'reply': '过道灯关了', 'undo': 'light_hallway_on'},
  'light_entry_on': {'device': '进门灯', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.lumi_acn018_8c45_right_switch_service', 'reply': '进门灯开了', 'undo': 'light_entry_off'},
  'light_entry_off': {'device': '进门灯', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.lumi_acn018_8c45_right_switch_service', 'reply': '进门灯关了', 'undo': 'light_entry_on'},
  'light_bed_main_on': {'device': '主卧灯', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.lumi_acn016_057b_switch', 'reply': '主卧灯开了', 'undo': 'light_bed_main_off'},
  'light_bed_main_off': {'device': '主卧灯', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.lumi_acn016_057b_switch', 'reply': '主卧灯关了', 'undo': 'light_bed_main_on'},
  'light_bed_second_on': {'device': '次卧灯', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.lumi_acn016_31a2_switch', 'reply': '次卧灯开了', 'undo': 'light_bed_second_off'},
  'light_bed_second_off': {'device': '次卧灯', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.lumi_acn016_31a2_switch', 'reply': '次卧灯关了', 'undo': 'light_bed_second_on'},
  'light_dryarea_on': {'device': '干区灯', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.lumi_acn016_7d1c_switch', 'reply': '干区灯开了', 'undo': 'light_dryarea_off'},
  'light_dryarea_off': {'device': '干区灯', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.lumi_acn016_7d1c_switch', 'reply': '干区灯关了', 'undo': 'light_dryarea_on'},
  'light_balcony_on': {'device': '阳台灯', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.lumi_acn032_6dbd_right_switch_service', 'reply': '阳台灯开了', 'undo': 'light_balcony_off'},
  'light_balcony_off': {'device': '阳台灯', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.lumi_acn032_6dbd_right_switch_service', 'reply': '阳台灯关了', 'undo': 'light_balcony_on'},
  'light_balcony_north_on': {'device': '北阳台灯', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.lumi_acn016_9842_switch', 'reply': '北阳台灯开了', 'undo': 'light_balcony_north_off'},
  'light_balcony_north_off': {'device': '北阳台灯', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.lumi_acn016_9842_switch', 'reply': '北阳台灯关了', 'undo': 'light_balcony_north_on'},
  'light_bath_on': {'device': '浴室灯', 'kind': 'hass_control', 'service': 'light.turn_on', 'entity': 'light.yeelink_v5_7a82_light_bath_heater', 'reply': '浴室灯开了', 'undo': 'light_bath_off'},
  'light_bath_off': {'device': '浴室灯', 'kind': 'hass_control', 'service': 'light.turn_off', 'entity': 'light.yeelink_v5_7a82_light_bath_heater', 'reply': '浴室灯关了', 'undo': 'light_bath_on'},
  'ac_living_on': {'device': '客厅空调', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.ke_ting_kong_diao', 'reply': '客厅空调开了', 'undo': 'ac_living_off'},
  'ac_living_off': {'device': '客厅空调', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.ke_ting_kong_diao', 'reply': '客厅空调关了', 'undo': 'ac_living_on'},
  'ac_bed_main_on': {'device': '主卧空调', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.zhu_wo_kong_diao_kai_guan_2', 'reply': '主卧空调开了', 'undo': 'ac_bed_main_off'},
  'ac_bed_main_off': {'device': '主卧空调', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.zhu_wo_kong_diao_kai_guan_2', 'reply': '主卧空调关了', 'undo': 'ac_bed_main_on'},
  'ac_bed_second_on': {'device': '次卧空调', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.ci_wo_kong_diao', 'reply': '次卧空调开了', 'undo': 'ac_bed_second_off'},
  'ac_bed_second_off': {'device': '次卧空调', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.ci_wo_kong_diao', 'reply': '次卧空调关了', 'undo': 'ac_bed_second_on'},
  'fresh_air_all_on': {'device': '全屋新风', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.xin_feng', 'reply': '全屋新风开了', 'undo': 'fresh_air_all_off'},
  'fresh_air_all_off': {'device': '全屋新风', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.xin_feng', 'reply': '全屋新风关了', 'undo': 'fresh_air_all_on'},
  'fresh_air_living_on': {'device': '客厅新风', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.zhu_wo_xin_feng', 'reply': '客厅新风开了', 'undo': 'fresh_air_living_off'},
  'fresh_air_living_off': {'device': '客厅新风', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.zhu_wo_xin_feng', 'reply': '客厅新风关了', 'undo': 'fresh_air_living_on'},
  'fresh_air_bed_main_on': {'device': '主卧新风', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.zhu_wo_xin_feng_2', 'reply': '主卧新风开了', 'undo': 'fresh_air_bed_main_off'},
  'fresh_air_bed_main_off': {'device': '主卧新风', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.zhu_wo_xin_feng_2', 'reply': '主卧新风关了', 'undo': 'fresh_air_bed_main_on'},
  'fresh_air_bed_second_on': {'device': '次卧新风', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.ci_wo_xin_feng', 'reply': '次卧新风开了', 'undo': 'fresh_air_bed_second_off'},
  'fresh_air_bed_second_off': {'device': '次卧新风', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.ci_wo_xin_feng', 'reply': '次卧新风关了', 'undo': 'fresh_air_bed_second_on'},
  'air_purifier_on': {'device': '空气净化器', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.zhimi_m1_d497_switch_status', 'reply': '空气净化器开了', 'undo': 'air_purifier_off'},
  'air_purifier_off': {'device': '空气净化器', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.zhimi_m1_d497_switch_status', 'reply': '空气净化器关了', 'undo': 'air_purifier_on'},
  'curtain_living_on': {'device': '客厅窗帘', 'kind': 'hass_control', 'service': 'cover.open_cover', 'entity': 'cover.lumi_hmcn02_69ac_curtain', 'reply': '客厅窗帘拉开了', 'undo': 'curtain_living_off'},
  'curtain_living_off': {'device': '客厅窗帘', 'kind': 'hass_control', 'service': 'cover.close_cover', 'entity': 'cover.lumi_hmcn02_69ac_curtain', 'reply': '客厅窗帘拉上了', 'undo': 'curtain_living_on'},
  'curtain_bed_main_on': {'device': '主卧窗帘', 'kind': 'hass_control', 'service': 'cover.open_cover', 'entity': 'cover.lumi_mcn005_7a69_curtain', 'reply': '主卧窗帘拉开了', 'undo': 'curtain_bed_main_off'},
  'curtain_bed_main_off': {'device': '主卧窗帘', 'kind': 'hass_control', 'service': 'cover.close_cover', 'entity': 'cover.lumi_mcn005_7a69_curtain', 'reply': '主卧窗帘拉上了', 'undo': 'curtain_bed_main_on'},
  'water_heater_on': {'device': '热水器', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.re_shui_qi', 'reply': '热水器开了', 'undo': 'water_heater_off'},
  'water_heater_off': {'device': '热水器', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.re_shui_qi', 'reply': '热水器关了', 'undo': 'water_heater_on'},
  'zero_cold_water_on': {'device': '零冷水', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.ling_leng_shui_kai_guan', 'reply': '零冷水开了', 'undo': 'zero_cold_water_off'},
  'zero_cold_water_off': {'device': '零冷水', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.ling_leng_shui_kai_guan', 'reply': '零冷水关了', 'undo': 'zero_cold_water_on'},
  'bath_heater_on': {'device': '浴霸风暖', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.yeelink_v5_7a82_heating', 'reply': '浴霸风暖开了', 'undo': 'bath_heater_off'},
  'bath_heater_off': {'device': '浴霸风暖', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.yeelink_v5_7a82_heating', 'reply': '浴霸风暖关了', 'undo': 'bath_heater_on'},
  'bath_vent_on': {'device': '浴室换气', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.yeelink_v5_7a82_ventilation', 'reply': '浴室换气开了', 'undo': 'bath_vent_off'},
  'bath_vent_off': {'device': '浴室换气', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.yeelink_v5_7a82_ventilation', 'reply': '浴室换气关了', 'undo': 'bath_vent_on'},
  'humidifier_living_on': {'device': '加湿器', 'kind': 'hass_control', 'service': 'humidifier.turn_on', 'entity': 'humidifier.leshow_jsq3_2ff2_humidifier', 'reply': '加湿器开了', 'undo': 'humidifier_living_off'},
  'humidifier_living_off': {'device': '加湿器', 'kind': 'hass_control', 'service': 'humidifier.turn_off', 'entity': 'humidifier.leshow_jsq3_2ff2_humidifier', 'reply': '加湿器关了', 'undo': 'humidifier_living_on'},
  'water_dispenser_on': {'device': '饮水机', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.zhi_neng_yin_shui_ji_power', 'reply': '饮水机开了', 'undo': 'water_dispenser_off'},
  'water_dispenser_off': {'device': '饮水机', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.zhi_neng_yin_shui_ji_power', 'reply': '饮水机关了', 'undo': 'water_dispenser_on'},
  'dryer_on': {'device': '干衣机', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.ac8226ae410c_onoffstatus', 'reply': '干衣机开了', 'undo': 'dryer_off'},
  'dryer_off': {'device': '干衣机', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.ac8226ae410c_onoffstatus', 'reply': '干衣机关了', 'undo': 'dryer_on'},
  'fish_tank_on': {'device': '鱼缸', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.hfjh_m100_8257_fish_tank', 'reply': '鱼缸开了', 'undo': 'fish_tank_off'},
  'fish_tank_off': {'device': '鱼缸', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.hfjh_m100_8257_fish_tank', 'reply': '鱼缸关了', 'undo': 'fish_tank_on'},
  'socket_entry_on': {'device': '玄关插座', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.cuco_v3_99d7_switch_status', 'reply': '玄关插座开了', 'undo': 'socket_entry_off'},
  'socket_entry_off': {'device': '玄关插座', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.cuco_v3_99d7_switch_status', 'reply': '玄关插座关了', 'undo': 'socket_entry_on'},
  'camera_living_on': {'device': '客厅摄像头', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.chuangmi_cn_268116121_ipc021_on_p_2_1', 'reply': '客厅摄像头开了', 'undo': 'camera_living_off'},
  'camera_living_off': {'device': '客厅摄像头', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.chuangmi_cn_268116121_ipc021_on_p_2_1', 'reply': '客厅摄像头关了', 'undo': 'camera_living_on'},
  'camera_dining_on': {'device': '餐厅摄像头', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.chuangmi_021a04_dfca_switch_status', 'reply': '餐厅摄像头开了', 'undo': 'camera_dining_off'},
  'camera_dining_off': {'device': '餐厅摄像头', 'kind': 'hass_control', 'service': 'switch.turn_off', 'entity': 'switch.chuangmi_021a04_dfca_switch_status', 'reply': '餐厅摄像头关了', 'undo': 'camera_dining_on'},
  'door_lock_on': {'device': '门禁', 'kind': 'hass_control', 'service': 'switch.turn_on', 'entity': 'switch.sonoff_100160b7b2', 'reply': '门禁开了', 'confirm': True},
}